services:

  keycloak:
    ## Use your local image
    image: keycloak-plugin
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_AUTH_SERVER_URL: http://localhost:8080/realms/oidc4vc/vci
      KEYCLOAK_REALM: oidc4vc
      PRE_AUTH_LIFESPAN: 10
      PRE_AUTH_LIFESPAN_TIME_UNIT: MINUTES
      TX_CODE_SIZE: 4
      TX_CODE_DESCRIPTION: "Transaction code for the user"
      TOKEN_EXPIRATION: 3600 # 1 hour
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    volumes:
      - ./import:/opt/keycloak/data/import/
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mail-hog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
